import {
  Player,
  Fixture,
  GameweekStatus,
  ManagerInfo,
  TransferTarget,
  LeagueStanding,
  TeamFixtures,
} from "./types";

export const TEAM_COLORS: Record<string, string> = {
  Arsenal: "#EF0107",
  "Aston Villa": "#670E36",
  Bournemouth: "#DA291C",
  Brentford: "#E30613",
  Brighton: "#0057B8",
  Chelsea: "#034694",
  "Crystal Palace": "#1B458F",
  Everton: "#003399",
  Fulham: "#000000",
  Ipswich: "#0044AA",
  Leicester: "#003090",
  Liverpool: "#C8102E",
  "Man City": "#6CABDD",
  "Man Utd": "#DA291C",
  Newcastle: "#241F20",
  "Nottm Forest": "#E53233",
  Southampton: "#D71920",
  Spurs: "#132257",
  "West Ham": "#7A263A",
  Wolves: "#FDB913",
};

export const POSITION_COLORS: Record<string, string> = {
  GKP: "#f59e0b",
  DEF: "#22c55e",
  MID: "#3b82f6",
  FWD: "#ef4444",
};

export const mockSquad: Player[] = [
  // Starting XI
  {
    id: 1,
    name: "Raya",
    team: "Arsenal",
    position: "GKP",
    price: 55,
    totalPoints: 112,
    gameweekPoints: 6,
    goals: 0,
    assists: 1,
    cleanSheets: 12,
    minutes: 2520,
    form: "5.8",
    selectedBy: "28.4%",
    expectedGoals: 0,
    expectedAssists: 0.3,
    expectedGoalInvolvements: 0.3,
    ictIndex: "42.1",
    bonusPoints: 14,
  },
  {
    id: 2,
    name: "Alexander-Arnold",
    team: "Liverpool",
    position: "DEF",
    price: 72,
    totalPoints: 138,
    gameweekPoints: 9,
    goals: 3,
    assists: 8,
    cleanSheets: 14,
    minutes: 2340,
    form: "7.2",
    selectedBy: "34.1%",
    expectedGoals: 2.1,
    expectedAssists: 6.8,
    expectedGoalInvolvements: 8.9,
    ictIndex: "98.4",
    bonusPoints: 22,
  },
  {
    id: 3,
    name: "Saliba",
    team: "Arsenal",
    position: "DEF",
    price: 58,
    totalPoints: 121,
    gameweekPoints: 6,
    goals: 2,
    assists: 1,
    cleanSheets: 13,
    minutes: 2520,
    form: "5.4",
    selectedBy: "31.2%",
    expectedGoals: 1.8,
    expectedAssists: 0.9,
    expectedGoalInvolvements: 2.7,
    ictIndex: "52.3",
    bonusPoints: 16,
  },
  {
    id: 4,
    name: "Gabriel",
    team: "Arsenal",
    position: "DEF",
    price: 54,
    totalPoints: 118,
    gameweekPoints: 6,
    goals: 4,
    assists: 1,
    cleanSheets: 13,
    minutes: 2430,
    form: "5.1",
    selectedBy: "22.7%",
    expectedGoals: 2.4,
    expectedAssists: 0.5,
    expectedGoalInvolvements: 2.9,
    ictIndex: "48.9",
    bonusPoints: 18,
  },
  {
    id: 5,
    name: "Salah",
    team: "Liverpool",
    position: "MID",
    price: 133,
    totalPoints: 198,
    gameweekPoints: 14,
    goals: 18,
    assists: 12,
    cleanSheets: 0,
    minutes: 2430,
    form: "9.8",
    selectedBy: "62.3%",
    isCaptain: true,
    expectedGoals: 16.2,
    expectedAssists: 9.1,
    expectedGoalInvolvements: 25.3,
    ictIndex: "298.7",
    bonusPoints: 32,
  },
  {
    id: 6,
    name: "Palmer",
    team: "Chelsea",
    position: "MID",
    price: 112,
    totalPoints: 182,
    gameweekPoints: 8,
    goals: 16,
    assists: 9,
    cleanSheets: 0,
    minutes: 2340,
    form: "8.4",
    selectedBy: "51.8%",
    expectedGoals: 13.8,
    expectedAssists: 7.4,
    expectedGoalInvolvements: 21.2,
    ictIndex: "267.3",
    bonusPoints: 28,
  },
  {
    id: 7,
    name: "Saka",
    team: "Arsenal",
    position: "MID",
    price: 101,
    totalPoints: 156,
    gameweekPoints: 3,
    goals: 10,
    assists: 11,
    cleanSheets: 0,
    minutes: 2160,
    form: "6.1",
    selectedBy: "38.9%",
    isViceCaptain: true,
    news: "Hamstring - 75% chance of playing",
    chanceOfPlaying: 75,
    expectedGoals: 8.9,
    expectedAssists: 9.2,
    expectedGoalInvolvements: 18.1,
    ictIndex: "224.1",
    bonusPoints: 24,
  },
  {
    id: 8,
    name: "Bruno Fernandes",
    team: "Man Utd",
    position: "MID",
    price: 86,
    totalPoints: 134,
    gameweekPoints: 2,
    goals: 7,
    assists: 8,
    cleanSheets: 0,
    minutes: 2520,
    form: "4.2",
    selectedBy: "18.4%",
    expectedGoals: 6.8,
    expectedAssists: 7.1,
    expectedGoalInvolvements: 13.9,
    ictIndex: "178.2",
    bonusPoints: 16,
  },
  {
    id: 9,
    name: "Haaland",
    team: "Man City",
    position: "FWD",
    price: 148,
    totalPoints: 172,
    gameweekPoints: 12,
    goals: 22,
    assists: 3,
    cleanSheets: 0,
    minutes: 2340,
    form: "8.9",
    selectedBy: "58.1%",
    expectedGoals: 20.4,
    expectedAssists: 2.8,
    expectedGoalInvolvements: 23.2,
    ictIndex: "312.4",
    bonusPoints: 30,
  },
  {
    id: 10,
    name: "Isak",
    team: "Newcastle",
    position: "FWD",
    price: 89,
    totalPoints: 148,
    gameweekPoints: 5,
    goals: 15,
    assists: 4,
    cleanSheets: 0,
    minutes: 2250,
    form: "7.1",
    selectedBy: "29.6%",
    expectedGoals: 13.2,
    expectedAssists: 3.1,
    expectedGoalInvolvements: 16.3,
    ictIndex: "198.6",
    bonusPoints: 22,
  },
  {
    id: 11,
    name: "Watkins",
    team: "Aston Villa",
    position: "FWD",
    price: 82,
    totalPoints: 132,
    gameweekPoints: 7,
    goals: 12,
    assists: 7,
    cleanSheets: 0,
    minutes: 2070,
    form: "6.8",
    selectedBy: "24.3%",
    expectedGoals: 10.8,
    expectedAssists: 5.6,
    expectedGoalInvolvements: 16.4,
    ictIndex: "186.2",
    bonusPoints: 18,
  },
  // Bench
  {
    id: 12,
    name: "Henderson",
    team: "Crystal Palace",
    position: "GKP",
    price: 45,
    totalPoints: 82,
    gameweekPoints: 1,
    goals: 0,
    assists: 0,
    cleanSheets: 6,
    minutes: 2520,
    form: "3.2",
    selectedBy: "8.4%",
    isBenched: true,
    expectedGoals: 0,
    expectedAssists: 0.1,
    expectedGoalInvolvements: 0.1,
    ictIndex: "18.4",
    bonusPoints: 6,
  },
  {
    id: 13,
    name: "Mykolenko",
    team: "Everton",
    position: "DEF",
    price: 43,
    totalPoints: 68,
    gameweekPoints: 1,
    goals: 0,
    assists: 2,
    cleanSheets: 5,
    minutes: 2160,
    form: "2.8",
    selectedBy: "4.2%",
    isBenched: true,
    expectedGoals: 0.2,
    expectedAssists: 1.4,
    expectedGoalInvolvements: 1.6,
    ictIndex: "32.1",
    bonusPoints: 4,
  },
  {
    id: 14,
    name: "Wissa",
    team: "Brentford",
    position: "MID",
    price: 61,
    totalPoints: 98,
    gameweekPoints: 2,
    goals: 6,
    assists: 3,
    cleanSheets: 0,
    minutes: 1890,
    form: "4.1",
    selectedBy: "9.1%",
    isBenched: true,
    expectedGoals: 5.4,
    expectedAssists: 2.8,
    expectedGoalInvolvements: 8.2,
    ictIndex: "112.3",
    bonusPoints: 8,
  },
  {
    id: 15,
    name: "Ndiaye",
    team: "Everton",
    position: "MID",
    price: 45,
    totalPoints: 52,
    gameweekPoints: 1,
    goals: 1,
    assists: 2,
    cleanSheets: 0,
    minutes: 1620,
    form: "2.1",
    selectedBy: "2.3%",
    isBenched: true,
    expectedGoals: 1.2,
    expectedAssists: 1.8,
    expectedGoalInvolvements: 3.0,
    ictIndex: "44.6",
    bonusPoints: 2,
  },
];

export const mockGameweek: GameweekStatus = {
  current: 28,
  deadlineTime: "2026-03-14T11:30:00Z",
  isActive: false,
  averageScore: 48,
  highestScore: 124,
  chipPlays: [
    { chip: "Bench Boost", count: 142891 },
    { chip: "Triple Captain", count: 98234 },
    { chip: "Free Hit", count: 67123 },
    { chip: "Wildcard", count: 234567 },
  ],
};

export const mockManager: ManagerInfo = {
  name: "FPL Manager",
  teamName: "War Room FC",
  overallRank: 42187,
  overallPoints: 1634,
  gameweekRank: 18923,
  gameweekPoints: 79,
  bank: 12,
  freeTransfers: 2,
  wildcardAvailable: true,
  benchBoostAvailable: true,
  tripleCaptainAvailable: false,
  freeHitAvailable: true,
};

export const mockFixtures: Fixture[] = [
  { id: 1, gameweek: 29, homeTeam: "Arsenal", awayTeam: "Brighton", kickoff: "2026-03-21T15:00:00Z", difficulty: 2, started: false, finished: false },
  { id: 2, gameweek: 29, homeTeam: "Liverpool", awayTeam: "Man Utd", kickoff: "2026-03-21T17:30:00Z", difficulty: 2, started: false, finished: false },
  { id: 3, gameweek: 29, homeTeam: "Wolves", awayTeam: "Chelsea", kickoff: "2026-03-21T15:00:00Z", difficulty: 2, started: false, finished: false },
  { id: 4, gameweek: 29, homeTeam: "Newcastle", awayTeam: "Spurs", kickoff: "2026-03-21T15:00:00Z", difficulty: 3, started: false, finished: false },
  { id: 5, gameweek: 29, homeTeam: "Man City", awayTeam: "Everton", kickoff: "2026-03-22T14:00:00Z", difficulty: 2, started: false, finished: false },
  { id: 6, gameweek: 29, homeTeam: "Aston Villa", awayTeam: "Fulham", kickoff: "2026-03-22T14:00:00Z", difficulty: 2, started: false, finished: false },
  { id: 7, gameweek: 29, homeTeam: "Bournemouth", awayTeam: "Leicester", kickoff: "2026-03-21T15:00:00Z", difficulty: 2, started: false, finished: false },
  { id: 8, gameweek: 29, homeTeam: "Brentford", awayTeam: "Crystal Palace", kickoff: "2026-03-21T15:00:00Z", difficulty: 3, started: false, finished: false },
  { id: 9, gameweek: 29, homeTeam: "Ipswich", awayTeam: "Nottm Forest", kickoff: "2026-03-22T16:30:00Z", difficulty: 4, started: false, finished: false },
  { id: 10, gameweek: 29, homeTeam: "Southampton", awayTeam: "West Ham", kickoff: "2026-03-21T15:00:00Z", difficulty: 3, started: false, finished: false },
];

export const mockTeamFixtures: TeamFixtures[] = [
  {
    team: "Arsenal", shortName: "ARS",
    fixtures: [
      { id: 101, gameweek: 29, homeTeam: "Arsenal", awayTeam: "Brighton", kickoff: "2026-03-21T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 102, gameweek: 30, homeTeam: "Fulham", awayTeam: "Arsenal", kickoff: "2026-03-28T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 103, gameweek: 31, homeTeam: "Arsenal", awayTeam: "Man City", kickoff: "2026-04-04T17:30:00Z", difficulty: 5, started: false, finished: false },
      { id: 104, gameweek: 32, homeTeam: "Newcastle", awayTeam: "Arsenal", kickoff: "2026-04-11T15:00:00Z", difficulty: 4, started: false, finished: false },
      { id: 105, gameweek: 33, homeTeam: "Arsenal", awayTeam: "Everton", kickoff: "2026-04-18T15:00:00Z", difficulty: 2, started: false, finished: false },
    ],
  },
  {
    team: "Liverpool", shortName: "LIV",
    fixtures: [
      { id: 201, gameweek: 29, homeTeam: "Liverpool", awayTeam: "Man Utd", kickoff: "2026-03-21T17:30:00Z", difficulty: 3, started: false, finished: false },
      { id: 202, gameweek: 30, homeTeam: "Spurs", awayTeam: "Liverpool", kickoff: "2026-03-28T17:30:00Z", difficulty: 3, started: false, finished: false },
      { id: 203, gameweek: 31, homeTeam: "Liverpool", awayTeam: "Wolves", kickoff: "2026-04-04T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 204, gameweek: 32, homeTeam: "Brighton", awayTeam: "Liverpool", kickoff: "2026-04-11T15:00:00Z", difficulty: 3, started: false, finished: false },
      { id: 205, gameweek: 33, homeTeam: "Liverpool", awayTeam: "Ipswich", kickoff: "2026-04-18T15:00:00Z", difficulty: 1, started: false, finished: false },
    ],
  },
  {
    team: "Chelsea", shortName: "CHE",
    fixtures: [
      { id: 301, gameweek: 29, homeTeam: "Wolves", awayTeam: "Chelsea", kickoff: "2026-03-21T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 302, gameweek: 30, homeTeam: "Chelsea", awayTeam: "Bournemouth", kickoff: "2026-03-28T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 303, gameweek: 31, homeTeam: "Leicester", awayTeam: "Chelsea", kickoff: "2026-04-04T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 304, gameweek: 32, homeTeam: "Chelsea", awayTeam: "Aston Villa", kickoff: "2026-04-11T15:00:00Z", difficulty: 3, started: false, finished: false },
      { id: 305, gameweek: 33, homeTeam: "Brentford", awayTeam: "Chelsea", kickoff: "2026-04-18T15:00:00Z", difficulty: 3, started: false, finished: false },
    ],
  },
  {
    team: "Man City", shortName: "MCI",
    fixtures: [
      { id: 401, gameweek: 29, homeTeam: "Man City", awayTeam: "Everton", kickoff: "2026-03-22T14:00:00Z", difficulty: 1, started: false, finished: false },
      { id: 402, gameweek: 30, homeTeam: "Southampton", awayTeam: "Man City", kickoff: "2026-03-28T15:00:00Z", difficulty: 1, started: false, finished: false },
      { id: 403, gameweek: 31, homeTeam: "Arsenal", awayTeam: "Man City", kickoff: "2026-04-04T17:30:00Z", difficulty: 5, started: false, finished: false },
      { id: 404, gameweek: 32, homeTeam: "Man City", awayTeam: "Crystal Palace", kickoff: "2026-04-11T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 405, gameweek: 33, homeTeam: "Fulham", awayTeam: "Man City", kickoff: "2026-04-18T15:00:00Z", difficulty: 2, started: false, finished: false },
    ],
  },
  {
    team: "Newcastle", shortName: "NEW",
    fixtures: [
      { id: 501, gameweek: 29, homeTeam: "Newcastle", awayTeam: "Spurs", kickoff: "2026-03-21T15:00:00Z", difficulty: 3, started: false, finished: false },
      { id: 502, gameweek: 30, homeTeam: "Ipswich", awayTeam: "Newcastle", kickoff: "2026-03-28T15:00:00Z", difficulty: 1, started: false, finished: false },
      { id: 503, gameweek: 31, homeTeam: "Newcastle", awayTeam: "West Ham", kickoff: "2026-04-04T15:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 504, gameweek: 32, homeTeam: "Newcastle", awayTeam: "Arsenal", kickoff: "2026-04-11T15:00:00Z", difficulty: 4, started: false, finished: false },
      { id: 505, gameweek: 33, homeTeam: "Everton", awayTeam: "Newcastle", kickoff: "2026-04-18T15:00:00Z", difficulty: 2, started: false, finished: false },
    ],
  },
  {
    team: "Aston Villa", shortName: "AVL",
    fixtures: [
      { id: 601, gameweek: 29, homeTeam: "Aston Villa", awayTeam: "Fulham", kickoff: "2026-03-22T14:00:00Z", difficulty: 2, started: false, finished: false },
      { id: 602, gameweek: 30, homeTeam: "Crystal Palace", awayTeam: "Aston Villa", kickoff: "2026-03-28T15:00:00Z", difficulty: 3, started: false, finished: false },
      { id: 603, gameweek: 31, homeTeam: "Aston Villa", awayTeam: "Nottm Forest", kickoff: "2026-04-04T15:00:00Z", difficulty: 3, started: false, finished: false },
      { id: 604, gameweek: 32, homeTeam: "Chelsea", awayTeam: "Aston Villa", kickoff: "2026-04-11T15:00:00Z", difficulty: 4, started: false, finished: false },
      { id: 605, gameweek: 33, homeTeam: "Aston Villa", awayTeam: "Leicester", kickoff: "2026-04-18T15:00:00Z", difficulty: 2, started: false, finished: false },
    ],
  },
];

export const mockTransferTargets: TransferTarget[] = [
  {
    playerIn: {
      id: 101, name: "Mbeumo", team: "Brentford", position: "MID", price: 78,
      totalPoints: 152, gameweekPoints: 11, goals: 12, assists: 7, cleanSheets: 0,
      minutes: 2340, form: "8.8", selectedBy: "32.1%",
      expectedGoals: 10.4, expectedAssists: 5.8, expectedGoalInvolvements: 16.2,
      ictIndex: "212.4", bonusPoints: 20,
    },
    playerOut: {
      id: 8, name: "Bruno Fernandes", team: "Man Utd", position: "MID", price: 86,
      totalPoints: 134, gameweekPoints: 2, goals: 7, assists: 8, cleanSheets: 0,
      minutes: 2520, form: "4.2", selectedBy: "18.4%",
      expectedGoals: 6.8, expectedAssists: 7.1, expectedGoalInvolvements: 13.9,
      ictIndex: "178.2", bonusPoints: 16,
    },
    netCost: -8,
    pointsGain: 4,
  },
  {
    playerIn: {
      id: 102, name: "Eze", team: "Crystal Palace", position: "MID", price: 69,
      totalPoints: 128, gameweekPoints: 7, goals: 8, assists: 6, cleanSheets: 0,
      minutes: 2070, form: "6.9", selectedBy: "14.8%",
      expectedGoals: 7.2, expectedAssists: 5.1, expectedGoalInvolvements: 12.3,
      ictIndex: "168.9", bonusPoints: 14,
    },
    playerOut: {
      id: 8, name: "Bruno Fernandes", team: "Man Utd", position: "MID", price: 86,
      totalPoints: 134, gameweekPoints: 2, goals: 7, assists: 8, cleanSheets: 0,
      minutes: 2520, form: "4.2", selectedBy: "18.4%",
      expectedGoals: 6.8, expectedAssists: 7.1, expectedGoalInvolvements: 13.9,
      ictIndex: "178.2", bonusPoints: 16,
    },
    netCost: -17,
    pointsGain: 2,
  },
  {
    playerIn: {
      id: 103, name: "Cunha", team: "Wolves", position: "FWD", price: 72,
      totalPoints: 142, gameweekPoints: 9, goals: 13, assists: 5, cleanSheets: 0,
      minutes: 2250, form: "7.8", selectedBy: "21.3%",
      expectedGoals: 11.4, expectedAssists: 4.2, expectedGoalInvolvements: 15.6,
      ictIndex: "196.7", bonusPoints: 18,
    },
    playerOut: {
      id: 11, name: "Watkins", team: "Aston Villa", position: "FWD", price: 82,
      totalPoints: 132, gameweekPoints: 7, goals: 12, assists: 7, cleanSheets: 0,
      minutes: 2070, form: "6.8", selectedBy: "24.3%",
      expectedGoals: 10.8, expectedAssists: 5.6, expectedGoalInvolvements: 16.4,
      ictIndex: "186.2", bonusPoints: 18,
    },
    netCost: -10,
    pointsGain: 3,
  },
];

export const mockLeague: LeagueStanding[] = [
  { rank: 1, managerName: "Dave's Dynasty", teamName: "The Invincibles", gameweekPoints: 92, totalPoints: 1712 },
  { rank: 2, managerName: "FPL Manager", teamName: "War Room FC", gameweekPoints: 79, totalPoints: 1634 },
  { rank: 3, managerName: "Sarah's Stars", teamName: "Goal Machine", gameweekPoints: 84, totalPoints: 1621 },
  { rank: 4, managerName: "Mike's Marvels", teamName: "Pep's Rejects", gameweekPoints: 68, totalPoints: 1598 },
  { rank: 5, managerName: "The Gaffer", teamName: "Set Piece Specialists", gameweekPoints: 71, totalPoints: 1584 },
  { rank: 6, managerName: "FPL Wizard", teamName: "Expected Threat XI", gameweekPoints: 55, totalPoints: 1567 },
  { rank: 7, managerName: "Captain Hindsight", teamName: "Knee Jerk United", gameweekPoints: 62, totalPoints: 1543 },
  { rank: 8, managerName: "Template Larry", teamName: "Copy Paste FC", gameweekPoints: 73, totalPoints: 1521 },
  { rank: 9, managerName: "Dead Team Dave", teamName: "GW1 And Done", gameweekPoints: 41, totalPoints: 1498 },
  { rank: 10, managerName: "Bottom Feeder", teamName: "Relegation Rovers", gameweekPoints: 38, totalPoints: 1432 },
];

export function getSquadValue(squad: Player[]): number {
  return squad.reduce((sum, p) => sum + p.price, 0);
}

export function formatPrice(tenths: number): string {
  return `£${(tenths / 10).toFixed(1)}m`;
}

export function getDifficultyColor(difficulty: number): string {
  switch (difficulty) {
    case 1: return "#00ff87";
    case 2: return "#01fc7a";
    case 3: return "#e7e7e7";
    case 4: return "#ff1751";
    case 5: return "#80072d";
    default: return "#e7e7e7";
  }
}

export function getDifficultyTextColor(difficulty: number): string {
  return difficulty >= 4 ? "#ffffff" : "#1a1a2e";
}
